# Base configs
baseurl: "https://thomasartopoulos.github.io/portfolio/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "vulgaris limes"
subtitle: "discovering frontiers"
author: "thomas artopoulos"
header:
 title: "map portfolio"
 subtitle: "by thomas artopoulos"
footer:
 name: "thomas artopoulos"
 bio: "estudio historia y me gusta la cartografía. aprendiendo nuevas formas de cartografiar."
 github: ""
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/thartopoulos"
  linkedin: "https://www.linkedin.com/in/thomasartopoulos/"
  github: "https://github.com/thomasartopoulos"
