# Base configs
baseurl: "https://thomasartopoulos.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "personal map portfolio"
subtitle: "discovering the world"
author: "thomas artopoulos"
header:
 title: "map portfolio"
 subtitle: "by thomas artopoulos"
footer:
 name: "thomas artopoulos"
 bio: "estudio historia y me gusta la cartografía. aprendiendo nuevas formas de cartografiar."
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
